trunk/website/config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: { sessions: "user/sessions", registrations: "user/registrations" }

  root to: 'main#index'

  get '/errors/internal_server_error' => 'errors#internal_server_error'
  get '/errors/not_found' => 'errors#not_found'
  get '/errors/unprocessable_entity' => 'errors#unprocessable_entity'

  get '/home' => 'main#home'

  get '/tire_samples/create' => 'tire_samples#create'

  resources :companies, :users, :sensors, :receivers, :tires, :tire_types, :tire_samples, :trailers, :trucks, :storages do
    member do
      get 'view_audit'
    end
  end

  resources :tire_sample_report, only: [:new, :create]

end

trunk/website/app/models/tire.rb
# $Id$
# $(c)$

class Tire < ActiveRecord::Base
  has_paper_trail

  belongs_to :tire_type
  belongs_to :using_company, class_name: 'Company'
  belongs_to :owning_company, class_name: 'Company'
  belongs_to :sensor
  belongs_to :tire_location

  validates_presence_of :using_company_id, :owning_company_id,
    :tire_type_id, :tire_location_id, :serial, message: 'must be provided'
  validate :tire_location_must_belong_to_using_company

  scope :all_tires, -> {
    active
    .joins(
      'left join (sensors, tire_types, companies as using_company, companies as owning_company, tire_locations) ' \
      'on (' +
      [
        'tires.sensor_id = sensors.id',
        'tires.tire_type_id = tire_types.id',
        'using_company.id = tires.using_company_id',
        'owning_company.id = tires.owning_company_id',
        'tires.tire_location_id = tire_locations.id'
      ].join(' and ') +
      ')'
    )
  }
  scope :active, -> {
    where(active: true)
  }

  scope :company, -> company_id {
    where(
      [
        "using_company_id = #{company_id}",
        "owning_company_id = #{company_id}"
      ].join(' or ')
    )
  }
  scope :contains, -> x {
    where(
      [
        "locate(\"#{x}\", tires.serial) > 0",
        "locate(\"#{x}\", sensors.serial) > 0",
        "locate(\"#{x}\", using_company.name) > 0",
        "locate(\"#{x}\", owning_company.name) > 0",
        "locate(\"#{x}\", tire_types.name) > 0"
      ].join(' or ')
    )
  }

  delegate :trucks, :trailers, :in_storage, to: :tire_location

  def name
    serial
  end

  def tire_type_name
    tire_type.name
  end

  def using_company_name
    using_company.name
  end

  def owning_company_name
    owning_company.name
  end

  def location_name
    tire_location.name
  end

  def sensor_serial
    sensor.try(:serial) || ''
  end

  def tire_location_must_belong_to_using_company
    unless tire_location.company_id == using_company_id
      errors.add(:using_company, 'must provide the tire location')
    end
  end

  def destroy
    self.active = false
    save!
  end
end

trunk/website/app/models/tire_type.rb
# $Id$
# $(c)$

class TireType < ActiveRecord::Base
  has_paper_trail
  has_many :tires

  validates_presence_of :name, message: 'must be provided'
  validates_uniqueness_of :name

  scope :all_tire_types, -> {
    active
  }
  scope :active, -> {
    where(active: true)
  }
  scope :company, -> company_id {
    joins(
      'LEFT JOIN `tires` ON tires.tire_type_id = tire_types.id'
    ).where(
      "tires.company_id = #{company_id}"
    )
  }
  scope :contains, -> x {
    where("locate(\"#{x}\", name) > 0")
  }

  def destroy
    self.active = false
    save!
  end
end

trunk/website/app/controllers/tires_controller.rb
# $Id$
# $(c)$

class TiresController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :find_tire, except: [:index, :new, :create]
  before_action :authenticate_user!

  def index
    smart_listing_create partial: 'tires/list',
      sort_attributes: [[:name, :serial], [:sensor_name, "sensors.serial"],
                        [:tire_type_name, "tire_types.name"], [:owning_company_name, "owning_company.name"],
                        [:using_company_name, "using_company.name"],
                        [:tire_location, "tire_locations.location_name" ]]
      end

  def new
    @tire = Tire.new
  end

  def show
  end

  def create
    @tire = Tire.create(tire_params)
  end

  def edit
  end

  def update
    @tire.transaction do
      @tire.update(tire_params)
    end
  end

  def destroy
    @tire.destroy
  end

  def view_audit
    @tire.touch_with_version if @tire.versions.empty?
  end

  def smart_listing_resource
    @tire ||= params[:id] ? Tire.find(params[:id]) : Tire.new(params[:tire])
  end
  helper_method :smart_listing_resource

  def smart_listing_collection
    scoped_tires = Tire.all_tires

    scoped_tires = scoped_tires.company(current_user.company_id) unless \
      current_user.global_admin?

    scoped_tires = scoped_tires.contains(params[:filter]) unless \
      params[:filter].blank?

    @tires ||= scoped_tires
  end
  helper_method :smart_listing_collection

  private

  def find_tire
    @tire = Tire.find(params[:id])
  end

  def tire_params
    tp = params.require(:tire).permit(
      :sensor_serial, :sensor_id, :using_company_id, :owning_company_id,
      :tire_type_id, :tire_location_id, :serial, :location_notation
    )

    if tp[:sensor_serial]
      tp[:sensor_id] = Sensor.find_by_serial(tp[:sensor_serial]).try(:id)
      tp.delete(:sensor_serial)
    end

    tp
  end
end

trunk/website/app/views/tires/_form.html.haml
- # $Id$
- # $(c)$

- locations = current_user.global_admin? ? TireLocation.all_locations : TireLocation.company_locations(current_user.company_id)

%td{colspan: 8}
  = render partial: 'components/form_error', formats: [:html], layout: false, locals: { object: object }
  = form_for object, url: object.new_record? ? tires_path : tire_path(object), remote: true, html: {class: "form-horizontal"} do |f|
    .field
      = f.label :serial_number
      \&nbsp;
      = f.text_field :serial, :size => 15, :autofocus => true
    .field
      = f.label :sensor_serial_number
      \&nbsp;
      = f.text_field :sensor_serial, :size => 15, :autofocus => true
    .field
      = f.label :tire_type
      \&nbsp;
      = f.collection_select :tire_type_id, TireType.all, :id, :name, :include_blank => 'No Tire Type Specified', autofocus: true
    .field
      = f.label :owning_company
      \&nbsp;
      = f.collection_select :owning_company_id, Company.all, :id, :name, :include_blank => 'No Company Specified', autofocus: true
    .field
      = f.label :using_company
      \&nbsp;
      = f.collection_select :using_company_id, Company.all, :id, :name, :include_blank => 'No Company Specified', autofocus: true
    .field
      = f.label :tire_location
      \&nbsp;
      = f.collection_select :tire_location_id, locations, :id, :name, :include_blank => 'No Location Specified', autofocus: true
    .field
      = f.label :location_notation
      \&nbsp;
      = f.text_field :location_notation, :size => 25, :autofocus => true

    = f.submit "Save", class: "btn btn-primary"
    %button.btn.btn-link.cancel Cancel

trunk/website/app/views/tires/_item.html.haml
- # $Id$
- # $(c)$

- actions = []
- if can? :view_audit, object
  - actions << {name: :custom,  icon: "glyphicon glyphicon-book", title: 'View Tire History', url: view_audit_tire_path(object)}
- if can? :edit, object
  - actions << {name: :edit,    url: edit_tire_path(object)}
- if can? :destroy, object
  - actions << {name: :destroy, url: tire_path(object), confirmation: "Are you sure you want to delete this tire?"}

%td= object.serial
%td= object.sensor_serial
%td= object.tire_type_name
%td= object.owning_company_name
%td= object.using_company_name
%td= object.location_name
%td= object.location_notation
%td.actions= smart_listing_item_actions [ *actions ]

trunk/website/app/views/tires/_list.html.haml
- # $Id$
- # $(c)$

- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %tr
        %th= smart_listing.sortable "Tire Serial", :name
        %th= smart_listing.sortable "Sensor Serial", :sensor_name
        %th= smart_listing.sortable "Tire Type", :tire_type_name
        %th= smart_listing.sortable "Owning Company", :owning_company_name
        %th= smart_listing.sortable "Using Company", :using_company_name
        %th= smart_listing.sortable "Tire Location", :tire_location
        %th Location Notation
        %th
    %tbody
      - smart_listing.collection.each do |tire|
        %tr.editable{data: {id: tire.id}}
          = smart_listing.render object: tire, partial: 'tires/item', locals: {object: tire}
    %tfoot
      = smart_listing.item_new colspan: 8, link: new_tire_path

  -# Render nice pagination links fitted for Bootstrap 3 by default
  .text-center
    = smart_listing.paginate
    = smart_listing.pagination_per_page_links

- else
  %p
    = smart_listing.item_new link: new_tire_path

trunk/website/app/views/tires/create.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :tires, :create, @tire, (@tire.valid? ? "tires/item" : "tires/form")

trunk/website/app/views/tires/destroy.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :tires, :destroy, @tire

trunk/website/app/views/tires/edit.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :tires, :edit, @tire, "tires/form"

trunk/website/app/views/tires/index.html.haml
- # $Id$
- # $(c)$

%h2 Tires

= smart_listing_controls_for(:tires, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off

  %button.btn.btn-primary.disabled{type: :submit}
    %span.glyphicon.glyphicon-search

= smart_listing_render :tires

trunk/website/app/views/tires/index.js.haml
- # $Id$
- # $(c)$

= smart_listing_update(:tires)

trunk/website/app/views/tires/new.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :tires, :new, @tire, "tires/form"

trunk/website/app/views/tires/show.html.haml
- # $Id$
- # $(c)$

%table.table.table-striped
  %thead
    %tr
      %th Tire Serial
      %th Sensor Serial
      %th Tire Type
      %th Owning Company
      %th Using Company
      %th Tire Location
      %th Location Notation
      %th Operations
  %tbody
    = render partial: 'tires/item', formats: [:html], layout: false, locals: { object: @tire }

trunk/website/app/views/tires/update.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :tires, :update, @tire, @tire.valid? ? "tires/item" : "tires/form"

trunk/website/app/views/tires/view_audit.html.haml
- # $Id$
- # $(c)$

= render partial: 'main/view_audit', formats: [:html], layout: false, locals: { object: @tire }