trunk/website/config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: { sessions: "user/sessions", registrations: "user/registrations" }

  root to: 'main#index'

  get '/errors/internal_server_error' => 'errors#internal_server_error'
  get '/errors/not_found' => 'errors#not_found'
  get '/errors/unprocessable_entity' => 'errors#unprocessable_entity'

  get '/home' => 'main#home'

  get '/tire_samples/create' => 'tire_samples#create'

  resources :companies, :users, :sensors, :receivers, :tires, :tire_types, :tire_samples, :trailers, :trucks, :storages do
    member do
      get 'view_audit'
    end
  end

  resources :tire_sample_report, only: [:new, :create]

end

trunk/website/app/models/company.rb
# $Id$
# $(c)$

class Company < ActiveRecord::Base
  has_paper_trail

  has_many :users

  validates_presence_of :name, :contact_name, :contact_address, :contact_phone,
    :contact_city, :contact_state, :contact_zip,
    message: 'must be provided'
  validates_date :start_service, :end_service
  validates_date :end_service, :after => :start_service, :on_or_before => :today

  scope :all_companies, -> {
    active
  }
  scope :active, -> {
    where(active: true)
  }
  scope :servicing, -> {
    where('(start_service is null or start_service <= NOW()) and ' \
          '(end_service >= NOW() or end_service is null)')
  }

  scope :my_company, -> company_id { where(id: company_id) }

  scope :contains, -> x {
    where(
      [
        "locate(\"#{x}\", name) > 0",
        "locate(\"#{x}\", contact_name) > 0",
        "locate(\"#{x}\", contact_address) > 0",
        "locate(\"#{x}\", contact_city) > 0",
        "locate(\"#{x}\", contact_state) > 0",
        "locate(\"#{x}\", contact_zip) > 0",
        "locate(\"#{x}\", contact_email) > 0"
      ].join(' or ')
    )
  }

  def destroy
    self.active = false
    save!
  end
end

trunk/website/app/controllers/companies_controller.rb
# $Id$
# $(c)$

class CompaniesController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :find_company, except: [:index, :new, :create]
  before_action :authenticate_user!

  def index
    smart_listing_create partial: 'companies/list'
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create(company_params)
  end

  def edit
  end

  def update
    @company.update(company_params)
  end

  def destroy
    @company.destroy
  end

  def view_audit
    @company.touch_with_version if @company.versions.empty?
  end

  def smart_listing_resource
    @company ||= params[:id] ? Company.find(params[:id]) : Company.new(params[:company])
  end
  helper_method :smart_listing_resource

  def smart_listing_collection
    scoped_companies = Company.all_companies

    scoped_companies = scoped_companies.my_company unless current_user.global_admin?

    scoped_companies = scoped_companies.contains(params[:filter]) unless params[:filter].blank?

    @companies ||= scoped_companies
  end
  helper_method :smart_listing_collection

  private

  def find_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :contact_name, :contact_address, :contact_phone,
                                    :contact_city, :contact_state, :contact_zip, :domain_name,
                                    :"start_service(1i)", :"start_service(2i)", :"start_service(3i)",
                                    :"end_service(1i)", :"end_service(2i)", :"end_service(3i)",
                                    :contact_email)
  end
end

trunk/website/app/views/companies/_form.html.haml
- # $Id$
- # $(c)$

%td{colspan: 12}
  = render partial: 'components/form_error', formats: [:html], layout: false, locals: { object: object }
  = form_for object, url: object.new_record? ? companies_path : company_path(object), remote: true, html: {class: "form-horizontal"} do |f|
    %table.table
      %tr
        %td{:colspan => 2}
          .field
            = f.label :name
            \&nbsp;
            = f.text_field :name, :size => 40, :autofocus => true
      %tr
        %td
          .field
            = f.label :start_service_date
            \&nbsp;
            = f.date_select :start_service, :autofocus => true
        %td
          .field
            = f.label :end_service_date
            \&nbsp;
            = f.date_select :end_service, :autofocus => true
      %tr
        %td{:colspan => 2}
          .field
            = f.label :contact_name
            \&nbsp;
            = f.text_field :contact_name, :size => 32, :autofocus => true
      %tr
        %td{:colspan => 2}
          .field
            = f.label :contact_street_address
            \&nbsp;
            = f.text_field :contact_address, :size => 64, :autofocus => true
      %tr
        %td{:colspan => 2}
          .field
            = f.label 'Contact City, State, and Zip'
            \&nbsp;
            = f.text_field :contact_city, :size => 40, :autofocus => true
            , &nbsp;
            = f.text_field :contact_state, :size => 4, :autofocus => true
            \&nbsp;
            = f.text_field :contact_zip, :size => 10, :autofocus => true
      %tr
        %td{:colspan => 2}
          .field
            = f.label :contact_phone
            \&nbsp;
            = f.text_field :contact_phone, :size => 15, :autofocus => true
      %tr
        %td{:colspan => 2}
          .field
            = f.label :contact_email
            \&nbsp;
            = f.text_field :contact_email, :size => 48, :autofocus => true
      %tr
        %td{:colspan => 2}
          .field
            = f.label :email_domain_name
            \&nbsp;
            = f.text_field :domain_name, :size => 32, :autofocus => true
      %tr
        %td{colspan:2}
          = f.submit "Save", class: "btn btn-primary"
          %button.btn.btn-link.cancel Cancel

trunk/website/app/views/companies/_item.html.haml
- # $Id$
- # $(c)$

- actions = []
- if can? :view_audit, object
  - actions << {name: :custom,  icon: "glyphicon glyphicon-book", title: 'View Company History', url: view_audit_company_path(object)}
- if can? :edit, object
  - actions << {name: :edit,    url: edit_company_path(object)}
- if can? :destroy, object
  - actions << {name: :destroy, url: company_path(object), confirmation: "Are you sure you want to delete this company?"}

%td= object.name
%td= object.start_service
%td= object.end_service
%td= object.contact_name
%td= object.contact_address
%td= object.contact_city
%td= object.contact_state
%td= object.contact_zip
%td= object.contact_phone
%td= object.contact_email
%td= object.domain_name
%td.actions= smart_listing_item_actions [ *actions ]

trunk/website/app/views/companies/_list.html.haml
- # $Id$
- # $(c)$

- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %tr
        %th= smart_listing.sortable "Company Name", :name
        %th= smart_listing.sortable "Start Date", :start_service
        %th= smart_listing.sortable "End Date", :end_service
        %th=  "Contact"
        %th=  "Address"
        %th=  "City"
        %th=  "St"
        %th=  "Zip"
        %th=  "Phone"
        %th=  "Email"
        %th=  "Email Domain"
        %th
    %tbody
      - smart_listing.collection.each do |company|
        %tr.editable{data: {id: company.id}}
          = smart_listing.render object: company, partial: 'companies/item', locals: {object: company}
    %tfoot
      = smart_listing.item_new colspan: 12, link: new_company_path

  -# Render nice pagination links fitted for Bootstrap 3 by default
  .text-center
    = smart_listing.paginate
    = smart_listing.pagination_per_page_links

- else
  %p
  %table.table
    = smart_listing.item_new colspan: 12, link: new_company_path

trunk/website/app/views/companies/create.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :companies, :create, @company, @company.valid? ? "companies/item" : "companies/form"

trunk/website/app/views/companies/destroy.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :companies, :destroy, @company

trunk/website/app/views/companies/edit.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :companies, :edit, @company, "companies/form"

trunk/website/app/views/companies/index.html.haml
- # $Id$
- # $(c)$

%h2 Company Information and Contacts

= smart_listing_controls_for(:companies, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off

  %button.btn.btn-primary.disabled{type: :submit}
    %span.glyphicon.glyphicon-search

= smart_listing_render :companies

trunk/website/app/views/companies/index.js.haml
- # $Id$
- # $(c)$

= smart_listing_update(:companies)

trunk/website/app/views/companies/new.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :companies, :new, @company, "companies/form"

trunk/website/app/views/companies/update.js.haml
- # $Id$
- # $(c)$

= smart_listing_item :companies, :update, @company, @company.valid? ? "companies/item" : "companies/form"

trunk/website/app/views/companies/view_audit.html.haml
- # $Id$
- # $(c)$

= render partial: 'main/view_audit', formats: [:html], layout: false, locals: { object: @company }