trunk/website/config/routes.rb
Rails.application.routes.draw do

  devise_for :user, controllers: { sessions: "user/sessions", registrations: "user/registrations" }

  root to: 'main#index'

  get '/errors/internal_server_error' => 'errors#internal_server_error'
  get '/errors/not_found' => 'errors#not_found'
  get '/errors/unprocessable_entity' => 'errors#unprocessable_entity'

  get '/home' => 'main#home'

  get '/tire_samples/create' => 'tire_samples#create'

  resources :companies, :users, :sensors, :receivers, :tires, :tire_types, :tire_samples, :trailers, :trucks, :storages do
    member do
      get 'view_audit'
    end
  end

  resources :tire_sample_report, only: [:new, :create]

end

trunk/website/app/models/trailer.rb
# $Id: tire_sample.rb 70 2015-04-27 04:11:23Z bmck_newco $
# $(c): Copyright 2015 by Newco $

class Trailer < TireLocation

  validates_presence_of :company_id, :trailer_serial, message: 'must be provided'
  validates_uniqueness_of :trailer_serial, scope: :company_id

  scope :all_trailers, -> {
    active
    .joins(
      'left join (companies) ' \
      'on (companies.id = company_id)'
    )
  }
  scope :active, -> {
    where(active: true)
  }
  scope :company, -> company_id { where(company_id: company_id) }

  scope :contains, -> x {
    where(
      [
        "locate(\"#{x}\", companies.name) > 0",
        "locate(\"#{x}\", trailer_serial) > 0"
      ].join(' or ')
    )
  }

  def name
    "Trailer #{trailer_serial} (#{company_name})"
  end

  def destroy
    self.active = false
    save!
  end
end

trunk/website/app/controllers/trailers_controller.rb
# $Id$
# $(c)$

class TrailersController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :find_trailer, except: [:index, :new, :create]
  before_action :authenticate_user!

  def index
    smart_listing_create partial: 'trailers/list',
      sort_attributes: [[:company_name, "companies.name"], [:serial, :truck_serial]]
  end

  def new
    @trailer = Trailer.new
  end

  def create
    @trailer = Trailer.create(trailer_params)
  end

  def edit
  end

  def update
    @trailer.update(trailer_params)
  end

  def destroy
    @trailer.destroy
  end

  def view_audit
    @trailer.touch_with_version if @trailer.versions.empty?
  end

  def smart_listing_resource
    @trailer ||= params[:id] ? Trailer.find(params[:id]) : Trailer.new(params[:trailer])
  end
  helper_method :smart_listing_resource

  def smart_listing_collection
    scoped_trailers = Trailer.all_trailers

    scoped_trailers = scoped_trailers.company(current_user.company_id) unless current_user.global_admin?

    scoped_trailers = scoped_trailers.contains(params[:filter]) unless params[:filter].blank?

    @trailers ||= scoped_trailers
  end
  helper_method :smart_listing_collection

  private

  def find_trailer
    @trailer = Trailer.find(params[:id])
  end

  def trailer_params
    params.require(:trailer).permit(:company_id, :trailer_serial, :location_name)
  end
end

trunk/website/app/views/trailers/_form.html.haml
- # $Id: _form.html.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

%td{colspan: 3}
  = render partial: 'components/form_error', formats: [:html], layout: false, locals: { object: object }
  = form_for object, url: object.new_record? ? trailers_path : trailer_path(object), remote: true, html: {class: "form-horizontal"} do |f|
    - if current_user.global_admin?
      .field
        = f.label :company_name
        \&nbsp;
        = f.collection_select :company_id, Company.all.to_a, :id, :name, autofocus: true
    - else
      = hidden_field_tag :company_id, current_user.company_id
    .field
      = f.label :trailer_serial
      \&nbsp;
      = f.text_field :trailer_serial, :size => 15, :autofocus => true
    = f.submit "Save", class: "btn btn-primary"
    %button.btn.btn-link.cancel Cancel

trunk/website/app/views/trailers/_item.html.haml
- # $Id: _item.html.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

- actions = []
- if can? :view_audit, object
  - actions << {name: :custom,  icon: "glyphicon glyphicon-book", title: 'View Trailer History', url: view_audit_trailer_path(object)}
- if can? :edit, object
  - actions << {name: :edit,    url: edit_trailer_path(object)}
- if can? :destroy, object
  - actions << {name: :destroy, url: trailer_path(object), confirmation: "Are you sure you want to delete this trailer?"}

%td= object.company_name
%td= object.name
%td.actions= smart_listing_item_actions [ *actions ]

trunk/website/app/views/trailers/_list.html.haml
- # $Id: _list.html.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %tr
        %th= smart_listing.sortable "Company", :company_name
        %th= smart_listing.sortable "Trailer Serial Number", :serial
        %th
    %tbody
      - smart_listing.collection.each do |trailer|
        %tr.editable{data: {id: trailer.id}}
          = smart_listing.render object: trailer, partial: 'trailers/item', locals: {object: trailer}
    %tfoot
      = smart_listing.item_new colspan: 3, link: new_trailer_path

  -# Render nice pagination links fitted for Bootstrap 3 by default
  .text-center
    = smart_listing.paginate
    = smart_listing.pagination_per_page_links

- else
  %p
  %table.table
    = smart_listing.item_new colspan: 1, link: new_trailer_path

trunk/website/app/views/trailers/create.js.haml
- # $Id: create.js.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

= smart_listing_item :trailers, :create, @trailer, @trailer.valid? ? "trailers/item" : "trailers/form"

trunk/website/app/views/trailers/destroy.js.haml
- # $Id: destroy.js.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

= smart_listing_item :trailers, :destroy, @trailer

trunk/website/app/views/trailers/edit.js.haml
- # $Id: edit.js.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

= smart_listing_item :trailers, :edit, @trailer, "trailers/form"

trunk/website/app/views/trailers/index.html.haml
- # $Id: index.html.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

%h2 Trailers

= smart_listing_controls_for(:trailers, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off

  %button.btn.btn-primary.disabled{type: :submit}
    %span.glyphicon.glyphicon-search

= smart_listing_render :trailers

trunk/website/app/views/trailers/index.js.haml
- # $Id: index.js.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

= smart_listing_update(:trailers)

trunk/website/app/views/trailers/new.js.haml
- # $Id: new.js.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

= smart_listing_item :trailers, :new, @trailer, "trailers/form"

trunk/website/app/views/trailers/update.js.haml
- # $Id: update.js.haml 56 2015-04-24 19:38:00Z bmck_newco $
- # $(c): Copyright 2015 by Newco $

= smart_listing_item :trailers, :update, @trailer, @trailer.valid? ? "trailers/item" : "trailers/form"

trunk/website/app/views/trailers/view_audit.html.haml
- # $Id$
- # $(c)$

= render partial: 'main/view_audit', formats: [:html], layout: false, locals: { object: @trailer }